# Generated by Django 5.1.6 on 2025-04-28 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aeroplane', '0009_holidaydeal'),
    ]

    operations = [
        migrations.AddField(
            model_name='holidaydeal',
            name='deal_image',
            field=models.ImageField(default='holiday_deal.jpg', upload_to='holiday_deals'),
        ),
    ]
